name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '12.x'
        distribution: 'adopt'
    - uses: subosito/flutter-action@v2.7.1
      with:
        flutter-version: '2.10.4'
    - run: flutter pub get
    - run: flutter build apk --debug
